package kimweng.cuscapi.com.greendao.db;

import java.util.Map;

import org.greenrobot.greendao.AbstractDao;
import org.greenrobot.greendao.AbstractDaoSession;
import org.greenrobot.greendao.database.Database;
import org.greenrobot.greendao.identityscope.IdentityScopeType;
import org.greenrobot.greendao.internal.DaoConfig;

import kimweng.cuscapi.com.greendao.POS;
import kimweng.cuscapi.com.greendao.Printer;
import kimweng.cuscapi.com.greendao.Shop;

import kimweng.cuscapi.com.greendao.db.POSDao;
import kimweng.cuscapi.com.greendao.db.PrinterDao;
import kimweng.cuscapi.com.greendao.db.ShopDao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT.

/**
 * {@inheritDoc}
 * 
 * @see org.greenrobot.greendao.AbstractDaoSession
 */
public class DaoSession extends AbstractDaoSession {

    private final DaoConfig pOSDaoConfig;
    private final DaoConfig printerDaoConfig;
    private final DaoConfig shopDaoConfig;

    private final POSDao pOSDao;
    private final PrinterDao printerDao;
    private final ShopDao shopDao;

    public DaoSession(Database db, IdentityScopeType type, Map<Class<? extends AbstractDao<?, ?>>, DaoConfig>
            daoConfigMap) {
        super(db);

        pOSDaoConfig = daoConfigMap.get(POSDao.class).clone();
        pOSDaoConfig.initIdentityScope(type);

        printerDaoConfig = daoConfigMap.get(PrinterDao.class).clone();
        printerDaoConfig.initIdentityScope(type);

        shopDaoConfig = daoConfigMap.get(ShopDao.class).clone();
        shopDaoConfig.initIdentityScope(type);

        pOSDao = new POSDao(pOSDaoConfig, this);
        printerDao = new PrinterDao(printerDaoConfig, this);
        shopDao = new ShopDao(shopDaoConfig, this);

        registerDao(POS.class, pOSDao);
        registerDao(Printer.class, printerDao);
        registerDao(Shop.class, shopDao);
    }
    
    public void clear() {
        pOSDaoConfig.clearIdentityScope();
        printerDaoConfig.clearIdentityScope();
        shopDaoConfig.clearIdentityScope();
    }

    public POSDao getPOSDao() {
        return pOSDao;
    }

    public PrinterDao getPrinterDao() {
        return printerDao;
    }

    public ShopDao getShopDao() {
        return shopDao;
    }

}
